### PR TITLE
[FIX] Wrong documentation related to the API usage

### LINKED ISSUE #77: Wrong doc for webhook private path
https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/09f12097cddb1be2dea1d461837774ed9fe501a1/src/definition/api/IApi.ts#L42

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #77

### CODE REVIEW

File: src/definition/api/ApiEndpoint.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ import { IApiResponse, IApiResponseJSON } from './IResponse';
  */
 export abstract class ApiEndpoint implements IApiEndpoint {
     /**
-     * Path to complete the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
+     * The final part of the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
```
Comment (graywolf336) [inline src/definition/api/ApiEndpoint.ts]:
```suggestion
     * The last part of the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
```

File: src/definition/api/IApiEndpoint.ts [hunk 2]
```diff
@@ -9,7 +9,7 @@ import { IApiResponse } from './IResponse';
  */
 export interface IApiEndpoint {
     /**
-     * Path to complete the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
+     * The final part of the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
```
Comment (graywolf336) [inline src/definition/api/IApiEndpoint.ts]:
```suggestion
     * The last part of the api URL. Example: https://{your-server-address}/api/apps/public/{your-app-id}/{path}
```

File: src/definition/api/IApi.ts [hunk 3]
```diff
@@ -39,7 +39,7 @@ export enum ApiVisibility {
      * including updates. As a result, if a user uninstalls the App
      * and reinstalls the App, then the random value will change.
      * Url format:
-     * `https://{your-server-address}/api/apps/private/{random-hash}/{your-app-id}/{path}`
+     * `https://{your-server-address}/api/apps/private//{your-app-id}{random-hash}/{path}`
```
Comment (graywolf336) [inline src/definition/api/IApi.ts]:
```suggestion
     * `https://{your-server-address}/api/apps/private/{your-app-id}/{random-hash}/{path}`
```
